### ISSUE TITLE
开了硬件加速，但是BlurDrawable还是无效

### ISSUE THREAD

**Issue by qinxianyuzou** [HokoFly/HokoBlur#11]
第一次执行无效，第二次app就闪退是为什么？我运行您的demo却没有问题。但是我看你的demo都没有配置什么东西，甚至硬件加速也只有MultiBlurActivity这个开了。
log只有：
` E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
 E/OpenGLRenderer: GL error: 0x506
 A/OpenGLRenderer: GL errors! frameworks/base/libs/hwui/BakedOpRenderer.cpp:98
 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 18772 (RenderThread)`

**Comment by HokoFly** [comment]
BlurDrawable的使用方式，代码提供一下
出现OpenGL ES API with no current context ，一般是当前线程没有初始化OpenGL的上下文信息导致的

**Comment by qinxianyuzou** [comment]
> BlurDrawable的使用方式，代码提供一下
> 出现OpenGL ES API with no current context ，一般是当前线程没有初始化OpenGL的上下文信息导致的

这个要怎么初始化上下文？我看你的demo也没有什么特殊的初始化操作吧？
我是直接部署了一个BlurFrameLayout，然后就报错了

**Comment by HokoFly** [comment]
检查下你的工程中指定opengl的版本
