### ISSUE TITLE
可否将 RenderScript 换成系统的

### ISSUE THREAD

**Issue by isMeiying** [HokoFly/HokoBlur#12]
android.renderscript 而不是 android.support.v8.renderscript

**Comment by Anzhi-Meiying** [comment]
并且我运行时直接闪退
![image](https://user-images.githubusercontent.com/13428030/57309248-4e676c80-711a-11e9-91cd-59e85a7c4719.png)

**Comment by HokoFly** [comment]
这是已知问题，和部分系统和机型有关，可以贴下你的这些信息

**Comment by Anzhi-Meiying** [comment]
@HokoFly 手机为小米Note3，系统为8.1.0，blurdrawable 可以换其他方案吗，比如 renderscript

**Comment by HokoFly** [comment]
使用support包是为了兼容4.0以下系统，如果没有必要兼容的话 ，可以替换

**Comment by Anzhi-Meiying** [comment]
@HokoFly 对的...我只适配了5.0+，可以多个选项吗，不用support包的

**Comment by HokoFly** [comment]
如果有个别的需求，可以单独编译打包的，暂时不会提供非support实现

**Comment by Anzhi-Meiying** [comment]
@HokoFly 好的，那么闪退是opengl的问题吗，是否能换成其他方案解决暂时解决这个问题

**Comment by HokoFly** [comment]
闪退和opengl的部分绘制参数错误有关，最近不太有时间排查这个问题，考虑过换成其他方案，但必须解决两个问题：
1. 获取实时需要重绘的区域
2. opengl的方案直接操作了底层FrameBuffer，效率不错，其他方案估计很难做到相同的绘制效率
