### ISSUE TITLE
Is it useful on VideoView? I need use it on VideoView to play video

### ISSUE THREAD

**Issue by Xiang0229** [HokoFly/HokoBlur#13]
Is it useful on VideoView? I need use it on VideoView to play video

**Comment by HokoFly** [comment]
Because the framebuffer is bound to the device screen, you have to modify that. However, the blur glsl script still could be reused

**Comment by Xiang0229** [comment]
可以说中文吗？我表示有点不懂

**Comment by HokoFly** [comment]
不能直接使用，因为现在屏上渲染时，FrameBuffer都是与设备屏幕绑定的，如果要用在VideoView上，需要在渲染绘制的时候，直接将模糊效果应用上去，所以模糊的GLSL代码还是可以复用的，但是其他绘制逻辑，绘制区域大小都需要你自己去控制了
