### ISSUE TITLE
opengl的shader的写法存在机型兼容性问题

### ISSUE THREAD

**Issue by liuhongda** [HokoFly/HokoBlur#14]
private static String getGaussianSampleCode() {

        StringBuilder sb = new StringBuilder();

        sb.append("   int diameter = 2 * uRadius + 1;  \n")
                .append("   vec4 sampleTex;\n")
                .append("   vec3 col;  \n")
                .append("   float weightSum = 0.0; \n")
                .append("   for(int i = 0; i < diameter; i++) {\n")
                .append("       vec2 offset = vec2(float(i - uRadius) * uWidthOffset, float(i - uRadius) * uHeightOffset);  \n")
                .append("       sampleTex = vec4(texture2D(uTexture, vTexCoord.st+offset));\n")
                .append("       float index = float(i); \n")
                .append("       float gaussWeight = getGaussWeight(index - float(diameter - 1)/2.0,")
                .append("           (float(diameter - 1)/2.0 + 1.0) / 2.0); \n")
                .append("       col += sampleTex.rgb * gaussWeight; \n")
                .append("       weightSum += gaussWeight;\n")
                .append("   }   \n")
                .append("   gl_FragColor = vec4(col / weightSum, sampleTex.a);   \n");

        return sb.toString();
    }
如上：vec3 col的写法最好写成vec3 col = vec3(0.0,0.0,0.0);主动进行初始化，否则在一些机型上会有问题，导致最终渲染效果不正确

**Comment by HokoFly** [comment]
已修复，感谢提醒
