### ISSUE TITLE
Mac 电脑中编译报错了，是要用Windows编译吗？

### ISSUE THREAD

**Issue by lxholding** [HokoFly/HokoBlur#15]
Skipped RenderScript support mode compilation for mips : required components not found in Build-Tools 28.0.3
Please check and update your BuildTools.
Skipped RenderScript support mode compilation for mips : required components not found in Build-Tools 28.0.3
Please check and update your BuildTools.
warning: Linking two modules of different data layouts: '/Users/lixin/work/android/sdk/build-tools/28.0.3/renderscript/lib/bc/armeabi-v7a/libclcore.bc' is 'e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64' whereas '/Users/lixin/work/git/HokoBlur/hoko-blur/build/generated/res/rs/debug/raw/bc32/boxblur.bc' is 'e-p:32:32-i64:64-v128:64:128-n32-S64'

warning: Linking two modules of different target triples: /Users/lixin/work/android/sdk/build-tools/28.0.3/renderscript/lib/bc/armeabi-v7a/libclcore.bc' is 'armv7--linux-android' whereas '/Users/lixin/work/git/HokoBlur/hoko-blur/build/generated/res/rs/debug/raw/bc32/boxblur.bc' is 'armv7-none-linux-gnueabi'

warning: Linking two modules of different data layouts: '/Users/lixin/work/android/sdk/build-tools/28.0.3/renderscript/lib/bc/armeabi-v7a/libclcore.bc' is 'e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64' whereas '/Users/lixin/work/git/HokoBlur/hoko-blur/build/generated/res/rs/debug/raw/bc32/stackblur.bc' is 'e-p:32:32-i64:64-v128:64:128-n32-S64'

warning: Linking two modules of different target triples: /Users/lixin/work/android/sdk/build-tools/28.0.3/renderscript/lib/bc/armeabi-v7a/libclcore.bc' is 'armv7--linux-android' whereas '/Users/lixin/work/git/HokoBlur/hoko-blur/build/generated/res/rs/debug/raw/bc32/stackblur.bc' is 'armv7-none-linux-gnueabi'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':hoko-blur:compileDebugRenderscript'.
> A problem occurred starting process 'command '/Users/lixin/work/android/sdk/build-tools/28.0.3/arm-linux-androideabi-ld''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
10 actionable tasks: 1 executed, 9 up-to-date
ERROR: Cause: error=86, Bad CPU type in executable

**Comment by HokoFly** [comment]
可能和你的系统版本有关，修改buildToolsVersion应该可以解决问题
