### ISSUE TITLE
Migrate from JCenter to MavenCentral

### ISSUE THREAD

**Issue by machiav3lli** [HokoFly/HokoBlur#18]
As JCenter will be shutting down fully soon, the migration to MavenCentral (preferably) is a must for the further use of the lib.
Here's a guide for that: https://jeroenmols.com/blog/2021/03/24/migrate-artifacts-mavencentral/

**Comment by bkoruznjak** [comment]
> As JCenter will be shutting down fully soon, the migration to MavenCentral (preferably) is a must for the further use of the lib.
> Here's a guide for that: https://jeroenmols.com/blog/2021/03/24/migrate-artifacts-mavencentral/

Not that its a great solution but to avoid linter warnings you can replace `jCenter()` with `gradlePluginPortal()` in your gradle till it gets migrated

**Comment by HokoFly** [comment]
> As JCenter will be shutting down fully soon, the migration to MavenCentral (preferably) is a must for the further use of the lib. Here's a guide for that: https://jeroenmols.com/blog/2021/03/24/migrate-artifacts-mavencentral/

I have migrated to MavenCentral.  Just try to use the dependency.

```groovy
   implementation 'io.github.hokofly:hoko-blur:1.3.6'
```

**Comment by machiav3lli** [comment]
Cool, thanks!
