### ISSUE TITLE
编译正常，运行报这个错

### ISSUE THREAD

**Issue by i91h1r** [HokoFly/HokoBlur#19]
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/armeabi-v7a/librs.stackblur.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

**Comment by HokoFly** [comment]
未复现，已升级AGP，可以再验证一下
