### ISSUE TITLE
请问现在版本支持TextureView和SurfaceView部分区域的动态模糊吗

### ISSUE THREAD

**Issue by hahafather007** [HokoFly/HokoBlur#2]

**Comment by HokoFly** [comment]
1. 动态模糊是以drawable的形式实现的，提供的是背景的动态模糊；
2. 理论上只要支持background drawable渲染的View，都可以添加动态模糊的效果；
3. 当前版本非动态的模糊，只支持普通View和Bitmap；
4. 如果需要给TextureView和SurfaceView添加模糊，可以参考Demo工程，有一个简易的对GLSurfaceView的模糊处理，但是因为你的需求是部分区域，可能还需要修改GLSL脚本来达到目的；

**Comment by hahafather007** [comment]
已经用另一种方法搞定了

**Comment by xie123** [comment]
> 已经用另一种方法搞定了
你用的啥方式做的？

**Comment by a741762308** [comment]
> 已经用另一种方法搞定了

请问大佬是怎么解决surfaceview的动态高斯的
