### ISSUE TITLE
能否将多个模糊模式分开

### ISSUE THREAD

**Issue by Anzhi-Meiying** [HokoFly/HokoBlur#5]
是否考虑将模糊方案和模糊模式分开，这样集成在一起会不会增大包的体积

**Comment by HokoFly** [comment]
包面积增加，原因有两个：
1. RenderScript的支持库 libRSSupport.so体积较大，占比最大的就是这个so；
2. 考虑到arm和x86的兼容，不同目标平台需要单独编译so

可以考虑单独打包RenderScript方案，其他方案和模式对包面积影响不大

**Comment by Anzhi-Meiying** [comment]
好的谢谢，RenderScript我是直接用的android.renderscript下面的，所以不知道有这个so

**Comment by HokoFly** [comment]
这是编译打包时自动引入的
