### ISSUE TITLE
Not working on Android Pie

### ISSUE THREAD

**Issue by danielzeller** [HokoFly/HokoBlur#6]
Hey, great library, love the performance of it. Any idea why the BlurDrawable.java does'nt work on Android Pie?

**Comment by HokoFly** [comment]
Have more detailed logs ?

I do not have an Android Pie device. So I just run the project on the simulator. And I just got an UnsatisfiedLinkError.

It seems that when compile the RenderScript code, only x86 platform dynamic libs are generated. But the libhoko_blur.so is built for the x86_64 platform. If the device is running on x86_64 platform, an 
UnsatisfiedLinkError will be thrown. Now I fixed the problem.

If your error is not an UnsatisfiedLinkError,  please show me the stacktrace.

**Comment by danielzeller** [comment]
`09-27 00:10:21.271 25849-25869/com.example.hokoblurdemo E/OpenGLRenderer: GL error:  GL_INVALID_OPERATION
09-27 00:10:21.271 25849-25869/com.example.hokoblurdemo A/OpenGLRenderer: glViewport error! GL_INVALID_OPERATION (0x502)
09-27 00:10:21.271 25849-25869/com.example.hokoblurdemo A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 25869 (RenderThread), pid 25849 (le.hokoblurdemo)`

Here is the Stacktrace. I'm using a Pixel 2 XL with Android 9. If you try running it on an emulator with Api level 28, it does'nt crash but the BlurDrawable renders nothing. Talking about the blurred background on MainActivity. 

It seems to be related to the GL drawing in ScreenBlurRenderer. If you comment away drawOneDimenBlur(..) and upscale(..) methods from  the onDrawFrame it does'nt crash but it naturally does not render anything eiter :)

**Comment by danielzeller** [comment]
Looks like  GLES20.glDrawElements(GLES20.GL_TRIANGLES, drawOrder.length, GLES20.GL_UNSIGNED_SHORT, mDrawListBuffer); makes it crash for some reason

**Comment by HokoFly** [comment]
If you run the project on the emulator of macOS, the BlurDrawable renders a strange effect. If you use the emulator of Windows, the BlurDrawable works normally. It seems to be related to difference of hardware render between these platforms.

I still cannot figure out just according to the GL_INVALID_OPERATION stacktrace. To solve it , I think I should try to get a device or add more GLError checks before calling glDrawElements method. GPU trace may be helpful.

**Comment by danielzeller** [comment]
I tried upgrading the shaders to Opengl 3.0, no longer crashes but nothing renders to the screen, works on Android Api level below 28 though 😌

**Comment by HokoFly** [comment]
Remove the dynamic blur

**Comment by HokoFly** [comment]
https://github.com/HokoFly/HokoBlurDrawable fix it
