### ISSUE TITLE
OverlayColor特性的支持

### ISSUE THREAD

**Issue by lucifinilsu** [HokoFly/HokoBlur#7]
在布局背景模糊或者动态模糊完成后，如果布局内的控件例如一个textview背景使用了android:background="?android:selectableItemBackground"，并赋予点击事件监听，当点击这个textview的时候，背景模糊效果会出现在textview区域内失效，我在你的demo里试验了这个问题，存在。

**Comment by HokoFly** [comment]
是在区域内失效 还是模糊效果在区域内了

**Comment by HokoFly** [comment]
按照你的测试方法，并没有复现你的问题，贴下你的系统版本和设备吧

**Comment by lucifinilsu** [comment]
> 表述清楚些 是在区域内失效 还是模糊效果作用在TextView上了

以下是我测试过程：

设备是小米4，6.0系统

首先，在你的demo首页布局activity_main里的BlurLinearLayout里添加
<TextView
            android:background="?android:selectableItemBackground"
            android:clickable="true"
            android:id="@+id/layout_blur_"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAllCaps="false"
            android:text="测试"/>

然后，在你的MainActivity里添加
private TextView tvBlur2;
private void initView() {
     ...
    tvBlur2=findViewById(R.id.layout_blur_);
        tvBlur2.setOnClickListener(this);
}
 @Override
 public void onClick(View view){
        ...
        case R.id.layout_blur_:

                break;
 }

然后运行。

点击“布局背景模糊”，这时，textview的背景和整个页面的背景是都是正常模糊的，然后我们点击textview，这时textview背景会出现水波纹效果，在水波纹效果过后，textview本身背景区域内的模糊效果消失。

**Comment by lucifinilsu** [comment]
> 表述清楚些 是在区域内失效 还是模糊效果作用在TextView上了
首页布局activity_main里的BlurLinearLayout里添加
`<TextView
            android:background="?android:selectableItemBackground"
            android:clickable="true"
            android:id="@+id/layout_blur_"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAllCaps="false"
            android:text="测试"/>`

**Comment by HokoFly** [comment]
2a4d6c58ae8db3edd1586b9dee403be5db8b3b71 尝试修复，1.2.2版本验证下

**Comment by lucifinilsu** [comment]
> [2a4d6c5](https://github.com/HokoFly/HokoBlur/commit/2a4d6c58ae8db3edd1586b9dee403be5db8b3b71) 尝试修复，1.2.2版本验证下

1.2.2版本，点击上述textview，水波纹消失后，textview背景模糊存在，但是能看清楚的看到textview的区域边界，似乎textview本身的模糊效果和整个页面的模糊效果是不同的，好像错位了一样。

**Comment by HokoFly** [comment]
是的 这是因为BlurDrawable只会对需要硬件重绘的区域添加模糊效果

1. 在未点击textview之前，会绘制整个Layout区域A；
2. 而点击TextView之后，由于水波纹效果的脏数据，只重绘TextView所在的区域B。
3. 两个不同区域，在计算TextView边界像素时，区域B由于缺少区域B以外的像素信息，所以会略微不同于于区域A；

并不推荐这种用法

**Comment by HokoFly** [comment]
1. 这个库是基于RenderScript实现的，因为是整个canvas去做的模糊，所以不会出现这个问题，但是RenderScript会有兼容性问题，特别是低版本系统，crash会比较多，以及因为是CPU密集型的功能，对于CPU性能较差的机型，亲测部分效果不太理想。

2. 这个问题并不是脏数据引起的，而是边界像素计算缺失导致的，改进的话还是有方法的；
3. realtimeOverlayColor的效果其实有考虑过实现的，但是相对工作量比较大；
4. 后续考虑会支持这两个特性，不过近期精力有限，并没有具体deadline；

**Comment by HokoFly** [comment]
欢迎PR

**Comment by lucifinilsu** [comment]
> 1. 这个库是基于RenderScript实现的，因为是整个canvas去做的模糊，所以不会出现这个问题，但是RenderScript会有兼容性问题，特别是低版本系统，crash会比较多，以及因为是CPU密集型的功能，对于CPU性能较差的机型，亲测部分效果不太理想。
> 2. 这个问题并不是脏数据引起的，而是边界像素计算缺失导致的，改进的话还是有方法的；
> 3. realtimeOverlayColor的效果其实有考虑过实现的，但是相对工作量比较大；
> 4. 后续考虑会支持这两个特性，不过近期精力有限，并没有具体deadline；
> 5. 欢迎PR

OK，再次谢谢您的解答，期待改进。

**Comment by HokoFly** [comment]
> > [2a4d6c5](https://github.com/HokoFly/HokoBlur/commit/2a4d6c58ae8db3edd1586b9dee403be5db8b3b71) 尝试修复，1.2.2版本验证下
> 
> 1.2.2版本，点击上述textview，水波纹消失后，textview背景模糊存在，但是能看清楚的看到textview的区域边界，似乎textview本身的模糊效果和整个页面的模糊效果是不同的，好像错位了一样。

@lucifinilsu  1.3.0版本已修复该问题
