### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by Neils320** [HokoFly/HokoBlur#8]
11-23 14:14:24.223 32679-321/com.amez.mall E/CrashReport-Native: Faile to open comm file(/system/build.prop)
11-23 14:14:24.441 32679-321/com.amez.mall E/CrashReport-Native: Failed to get java thread with thread name: RenderThread

在华为P9P的8.0.0上没有问题，在一加5的8.1.0上出现上面问题

**Comment by HokoFly** [comment]
没法单靠这两行crash日志做判断，有更详细的吗

**Comment by Neils320** [comment]
![1542954871 1](https://user-images.githubusercontent.com/8563181/48930669-0fa77680-ef2d-11e8-986a-f9b7024940e5.jpg)

**Comment by HokoFly** [comment]
11-23 14:14:24.223 32679-321/com.amez.mall E/CrashReport-Native: Faile to open comm file(/system/build.prop)
11-23 14:14:24.441 32679-321/com.amez.mall E/CrashReport-Native: Failed to get java thread with thread name: RenderThread

**Comment by Neils320** [comment]
不好意思，我这边就闪退时只有这些

**Comment by HokoFly** [comment]
把日志过滤器设为 No Filters 应该会有更多信息的

**Comment by HokoFly** [comment]
适当减少模糊半径，增加sampleFactor，mode改为stack blur
