### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by deletescape** [HokoFly/HokoBlur#9]
Hi,

I really like your Library and it's great at doing what it should do, we're now using it (or well our [slimmed down fork](https://github.com/LawnchairLauncher/hoko-lite) of it) in the V2 versions of Lawnchair Launcher. 

But exactly because we have made a fork I would be very glad if you could add some Open Source license to your library or at least clearly stated the licensing terms of it in the README. Without a license your library technically counts as proprietary and any fork or anyone modifying it/using parts of it is in danger of being sued by you if you ever decided to do so. 

If you're unsure which license to choose you can use <choosealicense.com> for a little help, or ask here.

**Comment by HokoFly** [comment]
Thanks for your suggestion. 😄 The license has been added and if there is still any problem, please let me know.

**Comment by deletescape** [comment]
Thanks a lot! And thanks for the great library again :tada:
